# Generated by Django 4.2.7 on 2023-11-17 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre_Material', models.CharField(max_length=20, verbose_name='material')),
            ],
        ),
        migrations.CreateModel(
            name='productor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=30)),
                ('Apellido', models.CharField(max_length=30)),
                ('Razon_Social', models.CharField(max_length=30, null=True)),
                ('DNI', models.CharField(max_length=30)),
                ('Domicilio', models.CharField(max_length=30)),
                ('Telefono', models.CharField(max_length=30)),
                ('Email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='email')),
            ],
            options={
                'verbose_name': 'productor',
                'verbose_name_plural': 'Productores',
                'db_table': 'productores',
                'ordering': ['Apellido'],
            },
        ),
        migrations.CreateModel(
            name='tipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.CharField(max_length=20, verbose_name='material')),
                ('descripcion', models.CharField(max_length=20, verbose_name='nombre')),
            ],
            options={
                'verbose_name': 'tipo',
                'verbose_name_plural': 'Tipos de material',
                'db_table': 'tipos',
                'ordering': ['descripcion'],
            },
        ),
    ]
