# Generated by Django 4.2.7 on 2023-11-18 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productor',
            options={'verbose_name': 'productor', 'verbose_name_plural': 'Productores'},
        ),
        migrations.CreateModel(
            name='envase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Descripción', models.CharField(max_length=30)),
                ('Material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.material')),
            ],
            options={
                'verbose_name': 'envase',
                'verbose_name_plural': 'Envases',
                'db_table': 'envases',
            },
        ),
    ]
