# Generated by Django 4.2.7 on 2023-11-18 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_productor_options_envase'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='envase',
            name='Descripción',
        ),
        migrations.AddField(
            model_name='envase',
            name='Descripcion',
            field=models.CharField(default='Bidón', max_length=30, verbose_name='descripción'),
        ),
        migrations.AlterField(
            model_name='envase',
            name='Material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.material'),
        ),
    ]
