# Generated by Django 4.2.7 on 2023-11-27 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_tipos_envases_unidad_delete_tipo_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='material',
            options={'verbose_name': 'material', 'verbose_name_plural': 'Materiales'},
        ),
        migrations.AlterModelOptions(
            name='tipos_envases',
            options={'verbose_name': 'tipos', 'verbose_name_plural': 'Tipos de envases'},
        ),
        migrations.AlterModelTable(
            name='material',
            table='materiales',
        ),
        migrations.AlterModelTable(
            name='tipos_envases',
            table='tipos_envases',
        ),
    ]
