# Generated by Django 4.2.7 on 2023-11-27 01:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_unidad_options_alter_unidad_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='unidad',
            options={'verbose_name': 'unidad', 'verbose_name_plural': 'U. de medidas'},
        ),
        migrations.CreateModel(
            name='ingreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cantidad', models.PositiveIntegerField(default=0)),
                ('Fecha', models.DateTimeField()),
                ('Envase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.envase')),
            ],
            options={
                'verbose_name': 'ingreso',
                'verbose_name_plural': 'Ingresos',
                'db_table': 'ingresos',
            },
        ),
    ]
