# Generated by Django 4.2.7 on 2023-11-27 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_unidad_options_ingreso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingreso',
            name='Fecha',
            field=models.DateField(),
        ),
    ]
