# Generated by Django 4.2.7 on 2023-12-16 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_ingreso_productor'),
    ]

    operations = [
        migrations.CreateModel(
            name='categorias_envases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=20, verbose_name='tipo de envase')),
            ],
            options={
                'verbose_name': 'categorias',
                'verbose_name_plural': 'Categorias de envases',
                'db_table': 'categorias_envases',
            },
        ),
        migrations.AddField(
            model_name='envase',
            name='Categoría',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.categorias_envases'),
        ),
    ]
