# Generated by Django 4.2.7 on 2023-12-19 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_categorias_envases_envase_categoría'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingreso',
            name='Retirado',
            field=models.BooleanField(default='False'),
        ),
    ]
